AllCops:
  Exclude:
    - '*.gemspec'

Style/EmptyLineBetweenDefs:
  Severity: error

Style/HashSyntax:
  Severity: error

Style/LineLength:
  Max: 120
  Severity: error

Style/MethodLength:
  Max: 25
  Severity: error

Style/TrailingWhitespace:
  Severity: error

Style/TrailingBlankLines:
  Severity: error

### Disabled checks

Documentation:
  Enabled: false

Style/SelfAssignment:
  Enabled: false
